### ISSUE TITLE
chrome.tabs.getSelected is deprecated

### ISSUE THREAD

**Issue by xatier** [tzangms/twitthat-chrome-extesion#1]
`chrome.tabs.getSelected` is deprecated since Chrome 33, need to change to `chrome.tabs.query`
- app.js

```
- chrome.tabs.getSelected(null, function(tab) {
+ chrome.tabs.query({ highlighted : true }, function(tab) {
```

Reference: https://developer.chrome.com/extensions/tabs#method-getSelected

**Comment by tzangms** [comment]
Done, thanks!

**Comment by xatier** [comment]
:+1:
